resolver: lts-15.6

packages:
  - .

extra-deps:
  - numhask-prelude-0.3.3
  - git: https://github.com/tonyday567/box
    commit: 8379b7efd7292878fd51b98128eff9313c557a61
  # - box-0.4.0
  - text-format-0.3.2

allow-newer: true

